name: Continuous Integration using Maven

on:
  push:
    branches: 
    - main
    - dev
    
    
jobs:
  build_project:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file WARZONE/pom.xml
      
#    - name: Run Tests with JUnit
 #     run: mvn test --file WARZONE/pom.xml
      
    - name: Generate Javadoc
      run: mvn javadoc:javadoc --file WARZONE/pom.xml

    - name: Publish Javadoc
      uses: actions/upload-artifact@v2
      with:
        name: javadoc -private *.java
        path: javadocs 
